apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: chathameedgsspringbootdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chathameedgsspringbootdocker 
    spec:
      containers:
        - name: chathameedgsspringbootdocker 
          image: hameedazurecontainerregistry.azurecr.io/chathameedgsspringbootdocker
          ports:
          - containerPort: 80